
genesis_id = ""
system = "Dogezer"
dependencies = ["Ethereum"]
icon = "dogezer"

[token]
name = "dgz token"
symbol = "DGZ"

[consensus]
consensus_type = "ERC20 Token"
consensus_name = "Ethereum"

[descriptions]
state = "Project"
system_type = "cryptoasset"
headline = "Do Software Together"

[crowdsales]
start_date = "2018-01-15T13:00:00"
end_date = "2018-03-08T13:00:00"
end_date_plan = "2018-03-08T13:00:00"
genesis_address = [""]
funding_terms = "https://dogezer.com/"
funding_url = "https://dogezer.com/"
tokens_sold = ""
tokens_issued = ""
btc_raised = ""
cap_limit = [""]
raised = [""]

[specs]
supply = 100000000

[[links]]
type = "website"
name = "dogezer.com"
url = "https://dogezer.com/"
tags = ["Main"]

[[links]]
type = "paper"
name = "Dogezer Whitepaper"
url = "https://dogezer.com/static/files/Dogezer_Whitepaper.pdf"
tags = ["Main", "Science"]

[[links]]
type = "github"
name = "Dogezer Github"
url = "https://github.com/akozlov-dogezer"
icon = "github.png"
tags = ["Main", "Code"]

[[links]]
type = "blog"
name = "Dogezer Blog"
url = "https://medium.com/@dogezercom"
icon = "medium.png"
tags = ["Main", "News"]

[[links]]
type = "forum"
name = "Bitcointalk"
url = "https://bitcointalk.org/index.php?topic=2100916.msg20998981"
icon = "bitcointalk.png"
tags = ["News"]

[[links]]
type = "twitter"
name = "Twitter"
url = "https://twitter.com/dogezerCom"
icon = "twitter.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Dogezer Telegram"
url = "https://t.me/dogezer"
icon = "telegram.png"
tags = ["News"]

[[links]]
type = "custom"
name = "Facebook"
url = "https://facebook.com/Dogezer-776538732528155"
icon = "facebook.png"
tags = ["News"]

[[links]]
type = "custom"
name = "YouTube"
url = "https://www.youtube.com/channel/UCxaU9UXzG7VvjHhnlmmSmJA"
icon = "youtube.png"
tags = ["News"]
